### PR TITLE
feat: Adjust logger to buffer 'debug' errors.

### PR DESCRIPTION
**Pull request by eugeingram**

### CODE REVIEW

**Comment by jimmythomson** [comment]
@eugeingram - could we default this buffering to off, and enable via an initialisation option?

**Comment by eugeingram** [comment]
> @eugeingram - could we default this buffering to off, and enable via an initialisation option?

@jimmythomson Sure, I can look at doing that.  By initialisation option do you mean an environment variable?

**Comment by jimmythomson** [comment]
With regard to the timestamp, you currently have for example:
```
'{"level":"error","data":[123,"test string",{"logTimestamp":1695859200000}]}',
```
Can we rename `logTimestamp` to just `timestamp` and make it a string? e.g.:
```
'{"level":"error", "timestamp":"2023-09-28T19:34:38.400Z", "data":[123,"test string"]}',
```

**Comment by jimmythomson** [comment]
> > @eugeingram - could we default this buffering to off, and enable via an initialisation option?
> 
> @jimmythomson Sure, I can look at doing that. By initialisation option do you mean an environment variable?

Ideally, we'd have it default to off, with that default controllable via an env var, but then overridable either when constructing a `Logger` object, or via a method such as `enableBuffering`.

**Comment by eugeingram** [comment]
> With regard to the timestamp, you currently have for example:
> 
> ```
> '{"level":"error","data":[123,"test string",{"logTimestamp":1695859200000}]}',
> ```
> 
> Can we rename `logTimestamp` to just `timestamp` and make it a string? e.g.:
> 
> ```
> '{"level":"error", "timestamp":"2023-09-28T19:34:38.400Z", "data":[123,"test string"]}',
> ```
> 
> Note that I've moved `timestamp` out of the `data` array an in to a top level property.

Okay, will do.

**Comment by eugeingram** [comment]
No longer required.

**Pull request closed without merging**
